#!/bin/bash
# init script for Opscenter.
# chkconfig: 2345 90 10
# description: Opscenter
# script slightly modified from 
 
. /etc/rc.d/init.d/functions
 
OPSCENTER_HOME=/usr/local/opscenter-3.0.2
OPSCENTER_BIN=$OPSCENTER_HOME/bin/opscenter
OPSCENTER_LOG=/var/log/opscenter/system.log
OPSCENTER_USER="root"
OPSCENTER_PID=/var/run/opscenter.pid
 
if [ ! -f $OPSCENTER_BIN ]; then
  echo "File not found: $OPSCENTER_BIN"
  exit 1
fi
 
RETVAL=0
 
start() {
  if [ -f $OPSCENTER_PID ] && checkpid `cat $OPSCENTER_PID`; then
    echo "Cassandra is already running."
    exit 0
  fi
  echo -n $"Starting $prog: "
  daemon --user $OPSCENTER_USER $OPSCENTER_BIN -p $OPSCENTER_PID >> $OPSCENTER_LOG 2>&1
  usleep 500000
  RETVAL=$?
  if [ "$RETVAL" = "0" ]; then
    echo_success
  else
    echo_failure
  fi
  echo
  return $RETVAL
}
 
stop() {
  # check if the process is already stopped by seeing if the pid file exists.
  if [ ! -f $OPSCENTER_PID ]; then
    echo "Opscenter is already stopped."
    exit 0
  fi
  echo -n $"Stopping $prog: "
  if kill `cat $OPSCENTER_PID`; then
    RETVAL=0
    echo_success
  else
    RETVAL=1
    echo_failure
  fi
  echo
  [ $RETVAL = 0 ]
}
 
status_fn() {
  if [ -f $OPSCENTER_PID ] && checkpid `cat $OPSCENTER_PID`; then
    echo "Opscenter is running."
    exit 0
  else
    echo "Opscenter is stopped."
    exit 1
  fi
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status_fn
    ;;
  restart)
    stop
	usleep 500000
    start
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status}"
    RETVAL=3
esac
 
exit $RETVAL
